print("simple calculator")
print("_____________________")
num1 = int(input("give me first number"))
num2 = int(input("give me second number"))
print("the operations performed are")
print("the addition is: " + str(num1+num2))
print("the multi is: " + str(num1*num2))
print("the subtraction is: " + str(num1-num2))
print("the division is: " + str(num1*num2))
